# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aka My Other Interest
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Musings on  programming. My journey through the land of computers and technology. A writing of a different, dryer sort. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ssunday.github.io/" # the base hostname & protocol for your site
twitter_username: sarahasunday
github_username:  ssunday

# Build settings
markdown: kramdown
