name: Aka My Other Interest
markdown: redcarpet
pygments: true
github: https://www.github.com/ssunday
about: Musings on my programming experiences and learning. My journey through the land of computers and technology. Something like writing.
urls:
    - text: github
      url: https://github.com/ssunday
    - text: twitter
      url: https://twitter.com/sarahasunday
baseurl: '/'
