# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AKA My Other Interest
description: Musings and writings of a programming and technical nature.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ssunday.github.io" # the base hostname & protocol for your site
twitter_username: sarahasunday
github_username:  ssunday

# Build settings
markdown: kramdown
