title: AKA My Tech Themed Blog
description: Rants about programming and technology. Also Emacs.
baseurl: ""
url: "http://ssunday.github.io"
twitter_username: sarahasunday
github_username:  ssunday

# Build settings
markdown: kramdown
