# Site settings
title: AKA My Other Interest
url: "http://ssunday.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/"
description: This is a blog containing musings and writings of a programming and technical nature. My journey through the land of computers and technology.


# Your information
author: Sarah Sunday
avatar: "http://ssunday.github.io/images/avatar.png"
profile: I'm a software apprentice.
#twitter_username: twitter_username
#github_username:  github_username

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
